### ISSUE TITLE
Error in CaptureRequest.java

### ISSUE THREAD

**Issue by gauravems** [mosip/mosip-mock-services#31]
Hi When we are trying to run the application;
The class CaptureRequest.java is throwing error at below line of code;

`HMACUtils.digestAsPlainText(HMACUtils.generateHash("".getBytes()))`

The error message is `java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter`

We are using Java version - java 11.0.6 2020-01-14 LTS

Detailed error 

```
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at io.mosip.kernel.core.util.HMACUtils.digestAsPlainText(HMACUtils.java:102) ~[kernel-core-1.0.8.jar:1.0.8]
	at org.biometric.provider.CaptureRequest.doAuthCapture(CaptureRequest.java:193) ~[classes/:na]
	at org.biometric.provider.CaptureRequest.doPost(CaptureRequest.java:93) ~[classes/:na]
	at org.biometric.provider.CaptureRequest.service(CaptureRequest.java:82) ~[classes/:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
```

**Comment by gauravems** [comment]
> Hi When we are trying to run the application;
> The class CaptureRequest.java is throwing error at below line of code;
> 
> `HMACUtils.digestAsPlainText(HMACUtils.generateHash("".getBytes()))`
> 
> The error message is `java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter`
> 
> We are using Java version - java 11.0.6 2020-01-14 LTS
> 
> Detailed error
> 
> ```
> java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
> 	at io.mosip.kernel.core.util.HMACUtils.digestAsPlainText(HMACUtils.java:102) ~[kernel-core-1.0.8.jar:1.0.8]
> 	at org.biometric.provider.CaptureRequest.doAuthCapture(CaptureRequest.java:193) ~[classes/:na]
> 	at org.biometric.provider.CaptureRequest.doPost(CaptureRequest.java:93) ~[classes/:na]
> 	at org.biometric.provider.CaptureRequest.service(CaptureRequest.java:82) ~[classes/:na]
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
> ```
